services:

  mysql:
    container_name: mysql-8.4.0
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: geometry
      MYSQL_DATABASE: SPRING
      MYSQL_USER: tmuser
      MYSQL_PASSWORD: tmuser
    ports:
      - 3306:3306
    volumes:
      - ~/dockerdata/mysqldata:/var/lib/mysql

  rest-app:
    image: localhost:5000/basic-rest-controller:1.0.2
    environment:
      SPRING_DATASOURCE_USERNAME: tmuser
      SPRING_DATASOURCE_PASSWORD: tmuser
      SPRING_JPA_HIBERNATE_DDLAUTO: update
      SPRING_PROFILES_ACTIVE: docker
    ports: 
      - 8080:8080

volumes:
  mydata:
