apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-webapp-deployment
  labels:
    app: person-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-webapp
  template:
    metadata:
      labels:
        app: person-webapp
    spec:
      containers:
      - name: person-webapp
        image: localhost:5000/basic-rest-controller:1.0.3
        ports:
        - containerPort: 8080
          name: app
        - containerPort: 5005
          name: debug
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-url
        - name: SPRING_PROFILES_ACTIVE
          value: rke
---
apiVersion: v1
kind: Service
metadata:
  name: person-webapp-service
spec:
  type: NodePort # default=ClusterIP
  selector:
    app: person-webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100
    - protocol: TCP
      port: 5005
      targetPort: 5005
