apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-webapp-deployment
  labels:
    app: person-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-webapp
  template:
    metadata:
      labels:
        app: person-webapp
    spec:
      containers:
      - name: person-webapp
        image: localhost:5000/basic-rest-controller:1.0.1
        ports:
        - containerPort: 8080
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
        - name: SPRING_PROFILES_ACTIVE
          value: rke
---
apiVersion: v1
kind: Service
metadata:
  name: person-webapp-service
spec:
  type: NodePort # default=ClusterIP
  selector:
    app: person-webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100