DROP DATABASE IF EXISTS SPRING;
DROP USER IF EXISTS `tempadmin`@`%`;
DROP USER IF EXISTS `tempuser`@`%`;

-- database
CREATE DATABASE IF NOT EXISTS SPRING CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- admin
CREATE USER IF NOT EXISTS `tempadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
-- privileges
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `SPRING`.* TO `tempadmin`@`%`;

-- user
CREATE USER IF NOT EXISTS `tempuser`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
-- privileges
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `SPRING`.* TO `tempuser`@`%`;

FLUSH PRIVILEGES;

USE SPRING;
DROP TABLE IF EXISTS `Person`;
CREATE TABLE `Person` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(32) NOT NULL,
  `AGE` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_NAME` (`NAME`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
