apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-rest-controller
  namespace: argocd # Namespace where Argo CD is running
spec:
  project: default
  source:
    repoURL: 'https://github.com/blurdel/BasicRestController'
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rest
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true