# Default values for mysql8
global:
  appPort: &appPort 8888
  mysqlPort: &mysqlPort 3306

replicas: 1
image:
  repository: localhost:5000/basic-rest-controller
  version: 1.0.4-beta3
  pullPolicy: IfNotPresent

ingress:
  host: basic-rest-controller.local

service:
  type: ClusterIP
  port: *appPort
  targetPort: *appPort
  debugPort: 5005

livenessProbe:
  httpGet:
    path: /health
    port: *appPort
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 7
readinessProbe:
  httpGet:
    path: /health
    port: *appPort
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 7

# MySQL Deployment
mysql:
  image:
    repository: mysql
    version: 8.4.0
    pullPolicy: IfNotPresent
    tag: ""
  serviceUrl: mysql-service
  rootPassword: c2VjcmV0
  database: SPRING
  user: dG11c2Vy
  password: dG11c2Vy

  service:
    type: ClusterIP
    port: *mysqlPort

  resources:
    limits:
      cpu: 0.5
      memory: 1Gi
    requests:
      cpu: 0.5
      memory: 1Gi

  livenessProbe:
    tcpSocket:
      port: *mysqlPort
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 5
  readinessProbe:
    tcpSocket:
      port: *mysqlPort
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 5
